apiVersion: v1
kind: Service
metadata:
  name: crate
  labels:
    app: crate
    tier: backend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
#  type: LoadBalancer
  ports:
  - port: 4200
    name: crate-web
  - port: 4300
    name: cluster
  - port: 5432
    name: crate-jdbc
  selector:
    app: crate
    tier: backend
